bingSearchTextInput = 'sb_form_q'
bingSearchButton = 'sb_form_go'
bingWebResult = '//*[@id="b-scopeListItem-web"]/a'
loginUsername = 'email'
loginPassword = 'password'
loginSubmit = 'submit'
loginAvevaPassword = 'passwordInput'
loginAvevaSubmit = 'submitButton'
loginMicrosoftNo = 'idBtn_Back'
logOutButton = '//span[@class=\'userbutton\']'
signOutButton = '//span[@id=\'actionmenuaction-4\']'
signHere = '//a[text()=\'here\']'
courseAllCourses = '//a[@title=\'All Courses\']'
coursePageNext = '//a[@aria-label=\'Next\']'
courseAVEVASimLMS = '//div[@class=\'info\']//a[text()=\'AVEVA SimLMS\']'
courseCategoryQA = '//div[@class=\'info\']//a[text()=\'QA\']'
courseCategoryAutomation = '//div[@class=\'info\']//a[text()=\'Automation\']'
courseTitleMultiAppLinkTest1 = '//div[@class=\'content\']/div[@class=\'summary\']//a[text()=\'Multi Applink Test 1\']'
courseTitleAutomationTestCourse = '//div[@class=\'content\']/div[@class=\'summary\']//a[text()=\'Carol Automation Test Course\']'
courseTopic1 = '//div[@class=\'content\']//a[text()=\'Topic 1\']'
courseActivities = '//div[@class=\'content\']//a[text()=\'Activities\']'
instanceMultiAppLinkTest1 = '//div[@class=\'activityinstance\']//a/span[text()=\'Multi Applink Test 1\']'
instanceAutomationTestProjectActivity = '//div[@class=\'activityinstance\']//a/span[text()=\'Automation Test Project Activity\']'
instanceLaunchButton = '//div[@class=\'singlebutton\']//button[text()=\'Open simulation in new window\']'
instanceSessionNO = '//div[@class=\'session-container\']//p[@class=\'instance-ref\']'
instanceSessionStatus = 'session-status'
connectSessionButton = '//div[@id=\'session-link\']/a[@id=\'instance-target\']'
editSettingButton = 'action-menu-0'
editTurnOn = '//div[@class=\'dropdown-item\']/a[text()=\'Turn editing on\']'
editActivitySetting = 'action-menu-1'
editSetting = '//div[@class=\'dropdown-item\']/a[text()=\'Edit settings\']'
exerciseSettings = '//div[@class=\'dropdown-item\']/a[text()=\'Exercise Settings\']'
expandAll = '//a[text()=\'Expand all\']'
exerciseGrade = 'id_gradepass'
editSettingSaveButton = 'id_submitbutton2'
editSettingCancelButton = 'id_cancel'
projectUpdateContinueButton = '//button[text()=\'Continue\']'
exerciseSettingSaveButton = 'id_submitbutton'
exerciseAttempt = 'id_attempts'
exerciseAttemptValue1 = '//select[@id=\'id_attempts\']/option[@value=\'1\']'
exerciseProject = 'id_projectid'
exerciseProjectMultiAPPLink = '//select[@id=\'id_projectid\']/option[text()=\'Multi-AppLink Test\']'
exerciseSetSelectRegion = 'id_userselectsregion'
exerciseSetSelectRegionNo = '//*[@id=\'id_userselectsregion\']/option[text()=\'No\']'
exerciseSetSelectRegionYes = '//*[@id=\'id_userselectsregion\']/option[text()=\'Yes\']'
exerciseDefaultRegion = 'id_region'
exerciseDefaultRegionCentralUS = '//*[@id=\'id_region\']/option[text()=\'Central US\']'
completionTypeSelectBox = 'id_completiontype'
completionTypeManual = '//option[text()=\'Manual\']'
completionTypeAutomatic = '//option[text()=\'Automatic\']'
completionTypeTimed = '//option[text()=\'Timed\']'
resultType = 'id_resultstype'
resultTypeFreePlay = '//*[@id=\'id_resultstype\']/option[text()=\'Free Play\']'
exerciseSettingsSaveButton = 'id_submitbutton'
exerciseEndButton = '//button[text()=\'End Exercise\']'
stopExerciseConfirmMessage = '//div[@id=\'modal-body\']/p'
stopExerciseConfirmButton = '//button[@class=\'btn btn-primary\']'
sessionEndedMessage = '//p[text()=\'Session ended\']'
thinfinityAlertBox = '//div[@class=\'alertBody\']'